format = """
$time\
[](fg:#22fc29)\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$python\
\n$character"""

[directory]
style = "fg:#22fc29"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#f18b46)]($style)'

[git_status]
untracked = '?${count} '
modified = '!${count} '
style = "bg:#394260"
format = '[[  ($all_status$ahead_behind)](fg:#f18b46)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[\[$time\] ](fg:#d4d608)]($style)'

[python]

